### PR TITLE
Replace Vector<T*> with Deque<T>

### LINKED ISSUE #60: Change type of _nodes from std::vector<Node<T>*> to std::vector<Node<T>>

### PR DESCRIPTION
**Pull request by ashaw596**
Replace Vector<T*> with Deque<T>. Also Changed alot of functions to const.

(edit by joshhting) Closes #60

### CODE REVIEW

**Comment by ashaw596** [comment]
Hmm, basically if we change to vector we have to change all the Nodes points to vector indexes since resizing vectors invalidates all the pointers. We could do that though I'm not sure about performance vs pointers, but I changed to Deque because it took me forever to figure out why the pointers were getting invalidated and Deque never invalidates.

**Comment by ashaw596** [comment]
Do you think we should change to vector and index? @justbuchanan

**Comment by justbuchanan** [comment]
Ahh that makes sense, I think I actually ran into that issue way back when I originally wrote that stuff.  Deque sounds good to me. Might be good to add a note in there explaining why you chose deque over vector.

**Comment by jgkamat** [comment]
Cool, I'm going to go ahead and merge this now, since we have 2 :+1:s

**Comment by joshhting** [comment]
Should we add the note explaining the use of deque first though?

**Comment by jgkamat** [comment]
oh whoops, heh

We can add that in another pr maybe? (guyys don't approve unless its ready :cry:)

**Comment by joshhting** [comment]
Yeah I guess that'd be more closely related to #56

**Comment by jgkamat** [comment]
We can add that as an item for #56. sounds good!

**Pull request merged**
