### PR TITLE
Improve getPath() methods and add better tests

### LINKED ISSUE #3: Test/fix getPath()

### PR DESCRIPTION
**Pull request by justbuchanan**
* return path directly as opposed to modifying by reference - return value optimization is your friend :)
* no mutable references - use pointers instead so intention is clearer at call site
* more tests for getPath() methods

closes #3

### CODE REVIEW

**Comment by jgkamat** [comment]
I completely forgot about this, sorry. I'll try to review this (or get josh/albert) to look over it soon.

**Comment by justbuchanan** [comment]
Yeah no worries, I sort of did half of this and left it, it still needs some work :)

**Comment by justbuchanan** [comment]
I think this is ready to go.

**Comment by jgkamat** [comment]
I'll try to take a look at this ASAP. Thanks! :smile:

**Pull request merged**
