### PR TITLE
added minIterations parameter. closes #52

### LINKED ISSUE #52: Add a min iterations parameter to RRT::Tree
Right now it returns the first path it finds, but sometimes it's best to continue running a bit longer to find a better path.  This would require modifying `RRT::Tree.run()`.

### PR DESCRIPTION
**Pull request by justbuchanan**
Closes #52 

TODO:

- [ ] ~track best solution in `RRT::Tree.run()`~
- [x] update docs
- [ ] add min iterations to gui
- [ ] ~more testing~

### CODE REVIEW

**Comment by jgkamat** [comment]
I haven't done too much work in the RRT, @joshhting, can you review this? I'll take a breif look over it too later.

Thanks @justbuchanan! :tada: :tada: :tada:

**Comment by joshhting** [comment]
Currently, the rrt-viewer never calls either run function. When you hit the run button (or the r key) it instead repeatedly calls RRTWidget::run_step() until it finds a path. Tree.hpp's run function is only called in the tests, and BiRRT.hpp's run function is never called in any of the rrt code. I'm assuming these are called in robocup-software, but as it currently stands we can't view this feature in action on the rrt-viewer, and it would be nice if we could.

**Comment by justbuchanan** [comment]
Good point, I forgot to add a note that this doesn't affect the gui.  I'll add a TODO for this.

**Comment by justbuchanan** [comment]
This should be good to go as well. I'll wait to add min iterations to the gui until after #54 is merged.

I ended up adding min iterations only to the BiRRT and not the single rrt (Tree.hpp). With a single rrt, after one solution is found, further iterations that choose random points near the goal will most likely only add  nodes to the existing solution rather than finding other unique solutions. In the BiRRT, the individual rrt trees don't really have a single goal point and instead meet the opposite tree in many locations. In this situation, continuing the search after finding one solution makes a lot more sense.

**Pull request merged**
