### PR TITLE
Use QML for gui

### PR DESCRIPTION
**Pull request by justbuchanan**
I did some work with QtQuick for another project and figured I'd try it out for the rrt gui and see how it works. I think it makes the gui code a lot easier to work with.  See the new main.qml file and compare to what was in MainWindow.cpp before. Rather than writing C++ code to add buttons, fields, etc, it can now be down in an html-like markup language.

Let me know what you guys think. If having yet another language (qml) to work in seems like too much, it's fine to drop this and stick with the C++ in place already.

TODO:

- [x] fix sizing of RRT widget and main window
- [x] button colors
- [x] fix relative path to qml file
- [x] cleanup and testing
- [x] ensure behavior and appearance are the same as before

### CODE REVIEW

**Comment by jgkamat** [comment]
I think that the move to QML is a good one, but it might be too much work to do that in soccer (the time might be better spent doing tuning or something else). Maybe getting this to work in soccer could be a good beginner project for someone interested in qt.

**Comment by justbuchanan** [comment]
Sounds good, I really like qml over doing gui code in c++. And qt designer ui files are a pain with git :/. Soccer would definitely be a good bit of work to port over, but luckily the rrt ui is pretty small :).

This needs a little more work before it's as good as before - I'll let you know when I get it fixed up.

**Comment by justbuchanan** [comment]
I think this is ready to be tested / reviewed. I tried to make it as close to the previous ui as possible, but let me know if anything is off.

Unfortunately there doesn't seem to be an easy way to change button colors in qml :/. See this forum thread for more info: https://forum.qt.io/topic/57647/qml-change-toolbar-color-one-style-property-only.

**Comment by justbuchanan** [comment]
Nice fix on the colors! Hopefully qml will make that type of thing easier in the future, but that works fine for now.

I think I have the resizing issue fixed - I just needed to set a fixed size on the rrt widget. Try it out and let me know if it works on your system.

**Comment by jgkamat** [comment]
Yup, this is perfect for me! Thanks! :smile: 

I'm :+1: on merging if you think it's good, go ahead and merge when you're ready :tada:

**Pull request merged**
