### PR TITLE
Added DoCIF setup for ci

### LINKED ISSUE #35: Use circleci and docif to speed up ci through caching

### PR DESCRIPTION
**Pull request by justbuchanan**
Here's a first attempt at setting up DoCIF (closes #35).  There are a couple issues though:

* GitHub status items aren't updating.  I copied the auth-tokens from the robocup circle.yml.  Are those repo-specific or just pat of the georgeburdell account?  Should DoCIF warn/error if GitHub auth fails here?
* Baseimage isn't getting pushed back to docker hub b/c I haven't added docker auth variables to circleci env.  Should DoCIF give a warning/error if it's configured to push back to the repo, but the variables aren't set right?

cc @jgkamat

### CODE REVIEW

**Comment by jgkamat** [comment]
Finally got a chance to look at this :smile: 

Status tokens weren't updating because georgeburdell didnt have access to this repo. That should be fixed now. (I need to add an error message when that happens or something)

About the baseimage push failure,
It does give a warning message. Unfortunately, theres no way to make my warning messages actually noticeable... If you look through the raw output of https://circleci.com/gh/RoboJackets/rrt/14 'buildbaseimage' step, there is a [WARN] message at the very bottom. I can't think of a better way of doing this other than that for now.

**Comment by justbuchanan** [comment]
Awesome, thanks for looking into this!

I'll get the docker variables setup so the baseimage can be cached, then I think this should all be working.

**Comment by justbuchanan** [comment]
@jgkamat can you email me the credentials for the burdell docker hub account?

**Comment by justbuchanan** [comment]
@jgkamat can you email me the credentials for the burdell docker hub account?

**Comment by jgkamat** [comment]
Yup, on the way!

**Pull request merged**
